
team_list = {
  133: {
  	'name': 'Oakland Athletics',
  	'teamName': 'Athletics',
  	'abbreviation': 'OAK',
  	'shortName': 'Oakland',
  	'locationName': 'Oakland',
  	'franchiseName': 'Oakland',
  	'clubName': 'Athletics',
  },
  134: {
  	'name': 'Pittsburgh Pirates',
  	'teamName': 'Pirates',
  	'abbreviation': 'PIT',
  	'shortName': 'Pittsburgh',
  	'locationName': 'Pittsburgh',
  	'franchiseName': 'Pittsburgh',
  	'clubName': 'Pirates',
  },
  135: {
  	'name': 'San Diego Padres',
  	'teamName': 'Padres',
  	'abbreviation': 'SD',
  	'shortName': 'San Diego',
  	'locationName': 'San Diego',
  	'franchiseName': 'San Diego',
  	'clubName': 'Padres',
  },
  136: {
  	'name': 'Seattle Mariners',
  	'teamName': 'Mariners',
  	'abbreviation': 'SEA',
  	'shortName': 'Seattle',
  	'locationName': 'Seattle',
  	'franchiseName': 'Seattle',
  	'clubName': 'Mariners',
  },
  137: {
  	'name': 'San Francisco Giants',
  	'teamName': 'Giants',
  	'abbreviation': 'SF',
  	'shortName': 'San Francisco',
  	'locationName': 'San Francisco',
  	'franchiseName': 'San Francisco',
  	'clubName': 'Giants',
  },
  138: {
  	'name': 'St. Louis Cardinals',
  	'teamName': 'Cardinals',
  	'abbreviation': 'STL',
  	'shortName': 'St. Louis',
  	'locationName': 'St. Louis',
  	'franchiseName': 'St. Louis',
  	'clubName': 'Cardinals',
  },
  139: {
  	'name': 'Tampa Bay Rays',
  	'teamName': 'Rays',
  	'abbreviation': 'TB',
  	'shortName': 'Tampa Bay',
  	'locationName': 'St. Petersburg',
  	'franchiseName': 'Tampa Bay',
  	'clubName': 'Rays',
  },
  140: {
  	'name': 'Texas Rangers',
  	'teamName': 'Rangers',
  	'abbreviation': 'TEX',
  	'shortName': 'Texas',
  	'locationName': 'Arlington',
  	'franchiseName': 'Texas',
  	'clubName': 'Rangers',
  },
  141: {
  	'name': 'Toronto Blue Jays',
  	'teamName': 'Blue Jays',
  	'abbreviation': 'TOR',
  	'shortName': 'Toronto',
  	'locationName': 'Toronto',
  	'franchiseName': 'Toronto',
  	'clubName': 'Blue Jays',
  },
  142: {
  	'name': 'Minnesota Twins',
  	'teamName': 'Twins',
  	'abbreviation': 'MIN',
  	'shortName': 'Minnesota',
  	'locationName': 'Minneapolis',
  	'franchiseName': 'Minnesota',
  	'clubName': 'Twins',
  },
  143: {
  	'name': 'Philadelphia Phillies',
  	'teamName': 'Phillies',
  	'abbreviation': 'PHI',
  	'shortName': 'Philadelphia',
  	'locationName': 'Philadelphia',
  	'franchiseName': 'Philadelphia',
  	'clubName': 'Phillies',
  },
  144: {
  	'name': 'Atlanta Braves',
  	'teamName': 'Braves',
  	'abbreviation': 'ATL',
  	'shortName': 'Atlanta',
  	'locationName': 'Atlanta',
  	'franchiseName': 'Atlanta',
  	'clubName': 'Braves',
  },
  145: {
  	'name': 'Chicago White Sox',
  	'teamName': 'White Sox',
  	'abbreviation': 'CWS',
  	'shortName': 'Chi White Sox',
  	'locationName': 'Chicago',
  	'franchiseName': 'Chicago',
  	'clubName': 'White Sox',
  },
  146: {
  	'name': 'Miami Marlins',
  	'teamName': 'Marlins',
  	'abbreviation': 'MIA',
  	'shortName': 'Miami',
  	'locationName': 'Miami',
  	'franchiseName': 'Miami',
  	'clubName': 'Marlins',
  },
  147: {
  	'name': 'New York Yankees',
  	'teamName': 'Yankees',
  	'abbreviation': 'NYY',
  	'shortName': 'NY Yankees',
  	'locationName': 'Bronx',
  	'franchiseName': 'New York',
  	'clubName': 'Yankees',
  },
  158: {
  	'name': 'Milwaukee Brewers',
  	'teamName': 'Brewers',
  	'abbreviation': 'MIL',
  	'shortName': 'Milwaukee',
  	'locationName': 'Milwaukee',
  	'franchiseName': 'Milwaukee',
  	'clubName': 'Brewers',
  },
  108: {
  	'name': 'Los Angeles Angels',
  	'teamName': 'Angels',
  	'abbreviation': 'LAA',
  	'shortName': 'LA Angels',
  	'locationName': 'Anaheim',
  	'franchiseName': 'Los Angeles',
  	'clubName': 'Angels',
  },
  109: {
  	'name': 'Arizona Diamondbacks',
  	'teamName': 'D-backs',
  	'abbreviation': 'AZ',
  	'shortName': 'Arizona',
  	'locationName': 'Phoenix',
  	'franchiseName': 'Arizona',
  	'clubName': 'Diamondbacks',
  },
  110: {
  	'name': 'Baltimore Orioles',
  	'teamName': 'Orioles',
  	'abbreviation': 'BAL',
  	'shortName': 'Baltimore',
  	'locationName': 'Baltimore',
  	'franchiseName': 'Baltimore',
  	'clubName': 'Orioles',
  },
  111: {
  	'name': 'Boston Red Sox',
  	'teamName': 'Red Sox',
  	'abbreviation': 'BOS',
  	'shortName': 'Boston',
  	'locationName': 'Boston',
  	'franchiseName': 'Boston',
  	'clubName': 'Red Sox',
  },
  112: {
  	'name': 'Chicago Cubs',
  	'teamName': 'Cubs',
  	'abbreviation': 'CHC',
  	'shortName': 'Chi Cubs',
  	'locationName': 'Chicago',
  	'franchiseName': 'Chicago',
  	'clubName': 'Cubs',
  },
  113: {
  	'name': 'Cincinnati Reds',
  	'teamName': 'Reds',
  	'abbreviation': 'CIN',
  	'shortName': 'Cincinnati',
  	'locationName': 'Cincinnati',
  	'franchiseName': 'Cincinnati',
  	'clubName': 'Reds',
  },
  114: {
  	'name': 'Cleveland Guardians',
  	'teamName': 'Guardians',
  	'abbreviation': 'CLE',
  	'shortName': 'Cleveland',
  	'locationName': 'Cleveland',
  	'franchiseName': 'Cleveland',
  	'clubName': 'Guardians',
  },
  115: {
  	'name': 'Colorado Rockies',
  	'teamName': 'Rockies',
  	'abbreviation': 'COL',
  	'shortName': 'Colorado',
  	'locationName': 'Denver',
  	'franchiseName': 'Colorado',
  	'clubName': 'Rockies',
  },
  116: {
  	'name': 'Detroit Tigers',
  	'teamName': 'Tigers',
  	'abbreviation': 'DET',
  	'shortName': 'Detroit',
  	'locationName': 'Detroit',
  	'franchiseName': 'Detroit',
  	'clubName': 'Tigers',
  },
  117: {
  	'name': 'Houston Astros',
  	'teamName': 'Astros',
  	'abbreviation': 'HOU',
  	'shortName': 'Houston',
  	'locationName': 'Houston',
  	'franchiseName': 'Houston',
  	'clubName': 'Astros',
  },
  118: {
  	'name': 'Kansas City Royals',
  	'teamName': 'Royals',
  	'abbreviation': 'KC',
  	'shortName': 'Kansas City',
  	'locationName': 'Kansas City',
  	'franchiseName': 'Kansas City',
  	'clubName': 'Royals',
  },
  119: {
  	'name': 'Los Angeles Dodgers',
  	'teamName': 'Dodgers',
  	'abbreviation': 'LAD',
  	'shortName': 'LA Dodgers',
  	'locationName': 'Los Angeles',
  	'franchiseName': 'Los Angeles',
  	'clubName': 'Dodgers',
  },
  120: {
  	'name': 'Washington Nationals',
  	'teamName': 'Nationals',
  	'abbreviation': 'WSH',
  	'shortName': 'Washington',
  	'locationName': 'Washington',
  	'franchiseName': 'Washington',
  	'clubName': 'Nationals',
  },
  121: {
  	'name': 'New York Mets',
  	'teamName': 'Mets',
  	'abbreviation': 'NYM',
  	'shortName': 'NY Mets',
  	'locationName': 'Flushing',
  	'franchiseName': 'New York',
  	'clubName': 'Mets',
  },
}
